abstract class OrderState{}
class InitState extends OrderState{}
class GetPickupPointLoadingState extends OrderState{}
class GetPickupPointSuccessState extends OrderState{}
class GetPickupPointErrorState extends OrderState{}
class GetStateByCountryLoadingState extends OrderState{}
class GetStateByCountrySuccessState extends OrderState{}
class GetStateByCountryErrorState extends OrderState{}
class ApplyCouponLoadingState extends OrderState{}
class ApplyCouponSuccessState extends OrderState{}
class ApplyCouponErrorState extends OrderState{}
class RemoveCouponLoadingState extends OrderState{}
class RemoveCouponSuccessState extends OrderState{}
class RemoveCouponErrorState extends OrderState{}
class GetCartSummaryLoadingState extends OrderState{}
class GetCartSummarySuccessState extends OrderState{}
class GetCartSummaryErrorState extends OrderState{}
class GetPaymentMethodLoadingState extends OrderState{}
class GetPaymentMethodSuccessState extends OrderState{}
class GetPaymentMethodErrorState extends OrderState{}
class GetUserAddressLoadingState extends OrderState{}
class GetUserAddressSuccessState extends OrderState{}
class GetUserAddressErrorState extends OrderState{}
class CreateUserAddressLoadingState extends OrderState{}
class CreateUserAddressSuccessState extends OrderState{}
class CreateUserAddressErrorState extends OrderState{}
class UpdateShippingTypeInCartLoadingState extends OrderState{}
class UpdateShippingTypeInCartSuccessState extends OrderState{}
class UpdateShippingTypeInCartErrorState extends OrderState{}
class UpdateOrderDateInCartLoadingState extends OrderState{}
class UpdateOrderDateInCartSuccessState extends OrderState{}
class UpdateOrderDateInCartErrorState extends OrderState{}
