abstract class ProductState{}
class InitState extends ProductState{}
class GetProductLoadingState extends ProductState{}
class GetProductSuccessState extends ProductState{}
class GetProductErrorState extends ProductState{}
class GetFeaturedProductLoadingState extends ProductState{}
class GetFeaturedProductSuccessState extends ProductState{}
class GetFeaturedProductErrorState extends ProductState{}
class GetProductOfCategoryLoadingState extends ProductState{}
class GetProductOfCategorySuccessState extends ProductState{}
class GetProductOfCategoryErrorState extends ProductState{}
class GetProductOfOfferLoadingState extends ProductState{}
class GetProductOfOfferSuccessState extends ProductState{}
class GetProductOfOfferErrorState extends ProductState{}

class GetProductOfOilLoadingState extends ProductState{}
class GetProductOfOilSuccessState extends ProductState{}
class GetProductOfOilErrorState extends ProductState{}
class GetProductOfBatteryLoadingState extends ProductState{}
class GetProductOfBatterySuccessState extends ProductState{}
class GetProductOfBatteryErrorState extends ProductState{}
class GetProductOfBrandLoadingState extends ProductState{}
class GetProductOfBrandSuccessState extends ProductState{}
class GetProductOfBrandErrorState extends ProductState{}
class GetSearchProductLoadingState extends ProductState{}
class GetSearchProductSuccessState extends ProductState{}
class GetSearchProductErrorState extends ProductState{}
class GetRelatedProductLoadingState extends ProductState{}
class GetRelatedProductSuccessState extends ProductState{}
class GetRelatedProductErrorState extends ProductState{}
class GetProductDetailsLoadingState extends ProductState{}
class GetProductDetailsSuccessState extends ProductState{}
class GetProductDetailsErrorState extends ProductState{}
